global:
    resolve_timeout: 2m
    #group_wait: 15s


route:
    receiver: 'slack'
    #    resolve_timeout: '5s'
    #group_wait: 5s
    #    repeat_interval: '10s'
receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#general'
            api_url: 'https://yourwebhookurl'
